### ISSUE TITLE
No radio stations are found (0.91)

### ISSUE THREAD

**Issue by rikdingemans** [santornl/nl.santor.vradio.homey#1]
For some reason not a single radio station is found when configuring and adding the VRadio card to a new flow.

**Comment by santornl** [comment]
Maybe it will help to disable the VRadio app and enable it again. The app will reload the radio stations.

**Comment by santornl** [comment]
Maybe it will help to disable the VRadio app and enable it again. The app will reload the radio stations.

**Comment by rikdingemans** [comment]
Thank you, this solved the issue
